### ISSUE TITLE
app name is misleading - change to chromeos_samba_network_file_share

### ISSUE THREAD

**Issue by wulvyrn** [GoogleChromeLabs/chromeos_network_file_share#103]
smb is not the only network file share.  nfs is also a network file share and this app doesn't support it.

**Comment by illiminable** [comment]
SMB functionality is now natively support in Chrome OS.

**Comment by illiminable** [comment]
Since Chrome 71, SMB is now natively supported by Chrome OS.

On Chrome 71 or higher you can:

Open the files app
Click the "three dot menu" in the top right
Choose "Add New Service"
Choose "SMB file share"

A dialog in settings will open (in 72 and later it's a standalone dialog). Enter your share information as before.

You can uninstall the chrome app as it will be deprecated in the near future. The new implementation is an order magnitude or two faster and much more reliable.

If you have bugs with the new implementation you can open them at crbug.com under component "Platform>Apps>FileManager"
