### ISSUE TITLE
Wrong filename appearing in music player

### ISSUE THREAD

**Issue by cottonwool** [GoogleChromeLabs/chromeos_network_file_share#37]
When accessing files via the _Network File Share_ on two occasions I have had the wrong file name appearing in the music player. This is a low impact issue.

I'm using two sources of SMB shares, a Win 7 PC and a Fritz Box modem / router. I will pay more attention which one I'm using when it happens.

On the second occasion I was using the Fritz Box as the SMB server.

This issue is intermittent or I haven't noticed the pattern to  reproduce it yet.

I have selected a file to be played by the standard Chrome OS music player and the filename shown has been that of the first file in a previously viewed directory, instead of the file selected to be played.

**Comment by illiminable** [comment]
I haven't seen this issue before. I'm not really sure how this could be possible (on the file system provider side) because files are opened by name. Does it stay with the wrong name or does it eventually correct itself?

I'll try and see if I can repro.

**Comment by cottonwool** [comment]
It seems to stay with the wrong name. I haven't seen it correct itself.
I've only seen it with the music player app.  It has occurred very rarely.

**Comment by illiminable** [comment]
Since Chrome 71, SMB is now natively supported by Chrome OS and this Chrome extension/app is deprecated. The new implementation is an order magnitude or two faster and much more reliable.

On Chrome 71 or higher you can:

Open the files app
Click the "three dot menu" in the top right
Choose "Add New Service"
Choose "SMB file share"

A dialog in settings will open (in 72 and later it's a standalone dialog). Enter your share information as before.

You can uninstall the chrome app as it will be deprecated in the near future. 

If you have bugs with the new implementation you can open them at crbug.com under component "Platform>Apps>FileManager"
