### ISSUE TITLE
Show info dialog when app is launched on non-Chrome OS platforms

### ISSUE THREAD

**Issue by dskaram** [GoogleChromeLabs/chromeos_network_file_share#38]
When app is launched on non-Chrome OS platforms, it currently tries to call API that doesn't exist and it just dies. Instead we should detect the platform and show an info dialog to users stating that this app is only support on Chrome OS.

**Comment by illiminable** [comment]
This is due to a bug in Chrome sync. The webstore knows to only serve this Chrome app to Chrome OS but the app sync isn't so smart and sync's it to all platforms and then it fails on startup on non-ChromeOS because it tries to call API's that don't exist.

2 parts to solution.

1) At app startup we need to check the platform. If it's not Chrome OS just silently skip all the start up code that tries to remount (on Chrome OS this happens intentionally happens at system start up). On other platforms it can happen the first time you start chrome after a reboot. There should be no user message in this case.

2) In the case where the UI of the app was explicitly opened, the regular mount dialog should show a message instead.

Need to investigate further if the user sees the message and deletes the app on say their linux machine will that deletion propagate back and delete it from CrOS too. For that reason we might have to be careful about how the message is worded.

Additionally follow up and see if there is a bug filed on chrome sync for this already.

**Comment by illiminable** [comment]
Since Chrome 71, SMB is now natively supported by Chrome OS and this Chrome extension/app is deprecated. The new implementation is an order magnitude or two faster and much more reliable.

On Chrome 71 or higher you can:

Open the files app
Click the "three dot menu" in the top right
Choose "Add New Service"
Choose "SMB file share"

A dialog in settings will open (in 72 and later it's a standalone dialog). Enter your share information as before.

You can uninstall the chrome app as it will be deprecated in the near future. 

If you have bugs with the new implementation you can open them at crbug.com under component "Platform>Apps>FileManager"
