### ISSUE TITLE
Image Preview/Gallery Not Loading Video Playback Unwatchable

### ISSUE THREAD

**Issue by ajsager** [GoogleChromeLabs/chromeos_network_file_share#47]
I am using an Acer Chromebook 14 and my drive is a MyBook Network drive.  I love that I can see the network files right in the file explorer on the Chromebook; however, the images previews do not load, and the gallery view never loads.  Videos stop so much they are not watchable.

**Comment by riverpro13** [comment]
Straight up it sounds like you have a memory problem  This can be caused by
your disk being to full  The Disk is also part of system memory which it
uses to swap in and out and deliver the pages that you see  If your disk is
more than 80% full then the problem will occur.
The other event may be that to many programs are open at the same time thus
using up memory.
Try doing some housekeeping and delete or archive the files / programs that
you do not use.  If this is not the problem then there may be a fault with
memory or a trojan / virus that you have contracted.
Go thru it a bit at a time and document what you do so that you can trace
back  Not seeing the device I cannot be sure but I hope these hints help

**Comment by ajsager** [comment]
I will look around, but the external drive is not even 50% full and the Chromebook was just unboxed yesterday.  The only programs running were Files and Chrome.  Is there a way to get into a developer mode on the Chromebook so I see the calls that are happening and see if there are any silent errors?

**Comment by riverpro13** [comment]
I dont know much about chromebook  but maybe in your settings check things
like java and see if you have pic displays disabled check chrome settings
also  check to see if you have suitable software for displaying your pic
content there are many and varied  google chrome has a place for adding
extensions also which you can avoid memory heavy programs  find a html5 ext
for displaying web and pics should be enough to get you underway

**Comment by illiminable** [comment]
Hi,

Sorry for the delay. It is currently by design that image previews are not shown. The reason is the only way to generate them is to download every image file which causes a lot of traffic and will make navigation very slow especially if you have a large folder of high res images.

In Nemo (file manager on Ubuntu) it also does not show image previews. On windows windows often generates a file called thumbs.db that contains small thumbnails. However as far as I know the format of that file is not documented.

In the future I will consider trying to at least make it a setting but in my testing it caused a lot of performance problems.

**Comment by ajsager** [comment]
Zentaro,

Thank you so much for your response.  I would love to see that as an option
in the future.  Let me know if you need any help beta testing if you do
ever implement it.

Thanks,
Adam

**Comment by illiminable** [comment]
Please note that for technical reasons thumbnails are still disabled.

Since Chrome 71, SMB is now natively supported by Chrome OS and this Chrome extension/app is deprecated. The new implementation is an order magnitude or two faster and much more reliable.

On Chrome 71 or higher you can:

Open the files app
Click the "three dot menu" in the top right
Choose "Add New Service"
Choose "SMB file share"

A dialog in settings will open (in 72 and later it's a standalone dialog). Enter your share information as before.

You can uninstall the chrome app as it will be deprecated in the near future. 

If you have bugs with the new implementation you can open them at crbug.com under component "Platform>Apps>FileManager"
