### ISSUE TITLE
Share could not be mounted

### ISSUE THREAD

**Issue by IsaacKieffer** [GoogleChromeLabs/chromeos_network_file_share#48]
I tried to mount a file for my new job and we were unable to share the mount? It says "share could not be mounted" 

We have the username and password correct, with case sensitivity. We also imputed the share bath as stated:  "//00.0.00.000/Files" With the correct numbers. 

Any help?

**Comment by IsaacKieffer** [comment]
Any help??

**Comment by illiminable** [comment]
Hi Isaac. Sorry for the delay.

Were you using back or forward slashes? It should look like this...

\\servername\files
or
\\123.123.123.123\files

Notice the \ not the /.

If you are still have trouble do the following to get the log.

1) Go to chrome://extensions in your browser
2) Scroll down until you see "Network File Share for Chrome OS"
3) Click on "plugin.html"
4) Select the "console" tab
5) Copy and paste the errors from the log.

Thanks!

**Comment by IsaacKieffer** [comment]
Thank you so much for getting back to me! I will try that when i get to the
office tomorrow!

**Comment by mlawrence85704** [comment]
I kept getting errors mounting the share until I tried the IP address of the window computer. 
Using the plugin.html mentioned above by Isaac, and the mount.html links in the logs at chrome://extensions/ I saw that it could not resolve the windows computer name,

Then I checked under settings under my wifi connection, under Network and NamesServers and saw that  the Chromebook was not using my router as a DNS server (apparently it defaults to Google DNS servers), so changed the first of the two values to match the gateway IP value, which I knew was my router IP, and then I was able to remove the mount and re-add it using the windows computer name instead of the IP address. It seems to be a bit slow, but it works.

**Comment by bentivegna** [comment]
I keep receiving the following errors in the log:
NACL ERROR: Error performing mount:smbc_opendir: errno=110 errtxt=Connection timed out
log.js:68 ERROR: rejecting message 60 SHOULD_RETRY
log.js:68 WARNING: mount[60] failed on attempt 1 of 3. Retrying...
log.js:24 NACL ERROR: Error performing mount:smbc_opendir: errno=110 errtxt=Connection timed out
log.js:68 ERROR: rejecting message 60 SHOULD_RETRY
log.js:68 WARNING: mount[60] failed on attempt 2 of 3. Retrying...
log.js:24 NACL ERROR: Error performing mount:smbc_opendir: errno=110 errtxt=Connection timed out
log.js:68 ERROR: rejecting message 60 SHOULD_RETRY
log.js:68 ERROR: mount[60] failed on attempt 3 of 3. Retrying...
log.js:68 ERROR: Mount with samba failed with FAILED
log.js:68 ERROR: Sending err response to popup
Anyone could help?

**Comment by illiminable** [comment]
SMB functionality has now been built natively into Chrome OS. On Chrome 71 or higher you can.

1) Open the files app
2) Click the "three dot menu" in the top right
3) Choose "Add New Service"
4) Choose "SMB file share"

A dialog in settings will open (in 72 and later it's a standalone dialog). Enter your share information as before.

You can uninstall the chrome app as it will be deprecated in the near future. The new implementation is an order magnitude or two faster and much more reliable.

If you have bugs with the new implementation you can open them at crbug.com under component "Platform>Apps>FileManager"

**Comment by illiminable** [comment]
FYI there will be no further development on this implementation.
