### ISSUE TITLE
support for end to end encryption

### ISSUE THREAD

**Issue by blackyellowred** [GoogleChromeLabs/chromeos_network_file_share#51]
in my smb config I set:
smb encrypt = mandatory
server signing = mandatory

server signing works but end to end encryption won't work. Support for was added in Samaba 3.2 and above. Please update the version that supports encryption. Thank You.

**Comment by blackyellowred** [comment]
It says Samba 4.1.22 is being used for this extension but my server is using samba 4.3.11

I still don't know why smb encrypt is not working.

**Comment by illiminable** [comment]
Depends on #59

**Comment by illiminable** [comment]
Note that SMB support is now native in Chrome OS. See http://crbug.com/921832 and http://crbug.com/904591 for the bugs tracking this feature there.

Since Chrome 71, SMB is now natively supported by Chrome OS and this Chrome extension/app is deprecated. The new implementation is an order magnitude or two faster and much more reliable.

On Chrome 71 or higher you can:

Open the files app
Click the "three dot menu" in the top right
Choose "Add New Service"
Choose "SMB file share"

A dialog in settings will open (in 72 and later it's a standalone dialog). Enter your share information as before.

You can uninstall the chrome app as it will be deprecated in the near future. 

If you have bugs with the new implementation you can open them at crbug.com under component "Platform>Apps>FileManager"
