### ISSUE TITLE
Investigate window loading without Polymer elements

### ISSUE THREAD

**Issue by allenktv** [GoogleChromeLabs/chromeos_network_file_share#84]
Sometimes when launching the app on CrOS in Linux, the app loads in an unfinished way. Only text is visible, and after a couple of seconds the Polymer elements fully load.

**Comment by allenktv** [comment]
I looked into this a little bit and found a few things:

1. I checked out the latest commit before I started making any commits [May 25th](https://github.com/GoogleChrome/chromeos_network_file_share/commit/61c24bff61674e013c7900a864b8958e7804fd3a) and saw that it was already happening, so this wasn't something that was recently introduced.
2. In `plugin.js` `chrome.app.runtime.onLaunched.addListener(loadForegroundPage)` is the code that loads the foreground page, and I am thinking that sometimes, that gets loaded before the Polymer elements are fully loaded. I believe the event for that is `WebComponentsReady`. This isn't a big help since we need to load the foreground page under the `chrome#onLaunched` callback.

I did see that it doesn't seem to happen on an actual CrOS device. I am guessing this is because the app runs in a very slow fashion while running on another machine. I am thinking that this may not be a huge issue, since we haven't heard complaints about it (since the version out in the store has the same symptoms).

**Comment by illiminable** [comment]
Closing old bugs.

Since Chrome 71, SMB is now natively supported by Chrome OS and this Chrome extension/app is deprecated. The new implementation is an order magnitude or two faster and much more reliable.

On Chrome 71 or higher you can:

Open the files app
Click the "three dot menu" in the top right
Choose "Add New Service"
Choose "SMB file share"

A dialog in settings will open (in 72 and later it's a standalone dialog). Enter your share information as before.

You can uninstall the chrome app as it will be deprecated in the near future. 

If you have bugs with the new implementation you can open them at crbug.com under component "Platform>Apps>FileManager"
