### ISSUE TITLE
Network share fails to mount

### ISSUE THREAD

**Issue by cagenti2** [GoogleChromeLabs/chromeos_network_file_share#91]
It worked nicely up to a few weeks ago, now network share (0.80.17230 ) fails to mount, i.e. it goes on indefinitely upon mounting without ever finding the shared drive.
Opening the "plugin.html" I find it appears NaCl crashed:

common.js:412 In common.js - DOMContentLoaded
plugin.html:1 NativeClient: NaCl module crashed

Chromebook is an ACER CB5-312T and Chrome OS is  62.0.3198.0 (Build ufficiale) dev (a 32 bit)

Please send suggestion on how to solve it!
Thanks
Carlo

**Comment by illiminable** [comment]
Can you let us know what device you are connecting to? Make and model of the storage device would be preferable.

**Comment by cagenti2** [comment]
That's a toshiba usb drive connected as shared drive to a Netgear D6200
router.
Thanks
Carlo

**Comment by illiminable** [comment]
This is most likely related to the last release disabling SMBv1 although I haven't seen it manifesting as a plugin crash before. More info about SMBv1 here...

https://blogs.technet.microsoft.com/filecab/2016/09/16/stop-using-smb1/
https://support.microsoft.com/en-us/help/4034314/smbv1-is-not-installed-by-default-in-windows-10-rs3-and-windows-server

We don't have one of those devices, but we have some other NetGear devices. Some of them can be upgraded. Though the other router I looked at Netgear WNDR4300 was not able to be updated.

A related thread https://community.netgear.com/t5/Using-your-ReadyNAS/Any-plans-for-Samba-fix-for-CVE-2017-7494/td-p/1290160

**Comment by cagenti2** [comment]
Shall I try an adress not in "smb synthax"? Would that overcome the problem?
The shared drive is windows formatted and on a windows lan...
Carlo

**Comment by cagenti2** [comment]
Checked and unfortunately my router is only smb v1.0 compatible with no v2
patch available.
Too bad
Thanks anyway
Carlo

**Comment by cagenti2** [comment]
Hello, 
I checked with local Netgear community(Italy) and  I was wrong: they confirm that the firmware of the 6200 router I am using is compoatible with smb2/3:

*Re: Readyshare su D6200: protocollo SMB solo v1?

Buongiorno Carlo,

 

Entrambe le versioni del protocollo SMB2/3 sono supportate dal l'ultimo firmware del D6200. 

 

Cordiali Saluti, 

Evelina

Team NETGEAR*

so it appears smbv1 compatibility shouldn't be the issue here. 
At this point which else may be the reason of the problem??
Thanks
Carlo

**Comment by crony1** [comment]
I'm seeing the same issue on a Samsung Chromebook Plus.  The NaCl error occurs right after clicking the "Share Path" field.

**Comment by illiminable** [comment]
Please note that SMB1 is not supported.

Since Chrome 71, SMB is now natively supported by Chrome OS and this Chrome extension/app is deprecated. The new implementation is an order magnitude or two faster and much more reliable.

On Chrome 71 or higher you can:

Open the files app
Click the "three dot menu" in the top right
Choose "Add New Service"
Choose "SMB file share"

A dialog in settings will open (in 72 and later it's a standalone dialog). Enter your share information as before.

You can uninstall the chrome app as it will be deprecated in the near future. 

If you have bugs with the new implementation you can open them at crbug.com under component "Platform>Apps>FileManager"
