### ISSUE TITLE
Clarify error message on mount fail

### ISSUE THREAD

**Issue by allenktv** [GoogleChromeLabs/chromeos_network_file_share#92]
Change toast to be more descriptive and add more verbose error logs

**Comment by illiminable** [comment]
Closing old bugs.

Since Chrome 71, SMB is now natively supported by Chrome OS.

On Chrome 71 or higher you can:

Open the files app
Click the "three dot menu" in the top right
Choose "Add New Service"
Choose "SMB file share"

A dialog in settings will open (in 72 and later it's a standalone dialog). Enter your share information as before.

You can uninstall the chrome app as it will be deprecated in the near future. The new implementation is an order magnitude or two faster and much more reliable.

If you have bugs with the new implementation you can open them at crbug.com under component "Platform>Apps>FileManager"
