### ISSUE TITLE
Firewall block on mounting shares?

### ISSUE THREAD

**Issue by Marcus-Safetec** [GoogleChromeLabs/chromeos_network_file_share#97]
I have mounted several shares on several clients but on this one client, it mounts successfully I can see the files and folders but a few seconds latter I loose access and can no long browse the shared folder, the client told me he has very strict firewall rules so I was wondering if the software tryes to contact the web and get's blocked somehow.

Any help is appreciated.

**Comment by stdouglas** [comment]
Up

**Comment by illiminable** [comment]
The app itself doesn't access the web. However the app is running as part of the chrome browser process and the browser does obviously access the net.

**Comment by Marcus-Safetec** [comment]
We noticed that the problem happens when we try to mount a share using an active directory user to authenticate, if we use a local user we can mount with no problem. The problen is most shared folders are on AD servers and there are no local users on these servers so we can't mount. Any ideias on why we're having this problems?

Thanks for the help!

**Comment by illiminable** [comment]
First obvious thing is make sure the domain name is part of the username for this case. Can you verify if the reason is because NTLM is disabled? I'll try and experiment with this scenario next week.

**Comment by stdouglas** [comment]
Seems not to be because NTLM is disabled once Kerberos would take care of authentication here, right?

**Comment by illiminable** [comment]
Since Chrome 71, SMB is now natively supported by Chrome OS and this Chrome extension/app is deprecated. The new implementation is an order magnitude or two faster and much more reliable.

On Chrome 71 or higher you can:

Open the files app
Click the "three dot menu" in the top right
Choose "Add New Service"
Choose "SMB file share"

A dialog in settings will open (in 72 and later it's a standalone dialog). Enter your share information as before.

You can uninstall the chrome app as it will be deprecated in the near future. 

If you have bugs with the new implementation you can open them at crbug.com under component "Platform>Apps>FileManager"
