### ISSUE TITLE
No authentication with AD user

### ISSUE THREAD

**Issue by stdouglas** [GoogleChromeLabs/chromeos_network_file_share#98]
Hello guys, good day

We are experiencing some odd issue here. While trying to connect a folder from a Windows 2008 R2 file server that is domain controller the mount fails every time as we use a domain user to authenticate...but when we try to mount a folder of a different ordinary server using a local user to authenticate it goes, no problem. Do you guys have any thoughts about it? I'm digging something about SMB and so, but seems unlikely since v2 are enabled.

Thanks for any help here!

**Comment by stdouglas** [comment]
Up

**Comment by illiminable** [comment]
Since Chrome 71, SMB is now natively supported by Chrome OS.

On Chrome 71 or higher you can:

Open the files app
Click the "three dot menu" in the top right
Choose "Add New Service"
Choose "SMB file share"

A dialog in settings will open (in 72 and later it's a standalone dialog). Enter your share information as before.

You can uninstall the chrome app as it will be deprecated in the near future. The new implementation is an order magnitude or two faster and much more reliable.

If you have bugs with the new implementation you can open them at crbug.com under component "Platform>Apps>FileManager"
